apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-static-deploymant
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: nginx
        ports:
        - containerPort: 80