apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-static-deploymant
  namespace: static
spec:
  selector:
    matchLabels:
      app: k8s-static-deploymant
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: k8s-static-deploymant
    spec:
      containers:
      - name: k8s-static-deploymant
        image: 161676990944.dkr.ecr.ap-south-1.amazonaws.com/k8s-static:latest
        ports:
        - containerPort: 80