apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: static
  labels:
    app: static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 774418219404.dkr.ecr.ca-central-1.amazonaws.com/k8s-static:1
        ports:
        - containerPort: 80