apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: static-ing
 namespace: static
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: sw.shaiksattarhadi.com
   http:
     paths:
     - backend:
         serviceName: myApp
         servicePort: 80
       path: /