apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: static
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  - hosts:
    - sw.shaiksattarhadi.com
    rules:
  - host: sw.shaiksattarhadi.com
    http:
      paths:
        - path: /apple
          backend:
            serviceName: service
            servicePort: 80
        