apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: static
spec:  
  rules:
  - host: king.shaiksattarhadi.com
    http:
      paths:
        backend:
          service:
            name: service
            port:
              number: 80
             
