apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-ingress-static
  namespace: static
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sw.shaiksattarhadi.com
    backend:
          service:
            name: static-service
            port:
              number: 80 
       
