apiVersion: networking.k8s.io/v1 Ingress
kind: Ingress
metadata:
 name: static-ingress
 namespace: static
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: ds.shaiksattarhadi.com
   http:
     paths:
     - path:
       backend:
         serviceName: k8s-static-svc
         servicePort: 80