apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-static
  namespace: static
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: http://sw.shaiksattarhadi.com/
    http:
      paths:
      - backend:
          serviceName: static-service
          servicePort: 80
        path: /