apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-ingress-static
  namespace: static
spec:
  rules:
  - host: sw.shaiksattarhadi.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: static-service
            port:
              number: 80
