apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:

  name: ingress-wildcard-host
  name: static

spec:
  rules:
  - host: "sw.shaiksattarhadi.com"
    http:
      paths:
      - pathType: Prefix
        path: 
        backend:
          service:
            name: service1
            port:
              number: 80