apiVersion: v1
kind: Service
metadata:
  name: app4-svc
  namespace: app4
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-2048
