apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: static

spec:
  type: LoadBalancer
  selector: 
    app: deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
